name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Install playwright browsers
        run: npx playwright install --with-deps
      
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # - run: npm i
      # - run: npm run build

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      #     if_key_exists: replace

      - name: Deploy to Production server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-o StrictHostKeyChecking=no"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /home/signageful-web/apps/signageful-web

      # - name: Deploy using ssh
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       cd /home/signageful-web/apps/signageful-web
      #       git pull origin main
      #       git status
      #       npm i
      #       npm run build --if-present
      #       npm test